services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: carparts_db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "P@rola123"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sql_data:
